apiVersion: v1
kind: Service
metadata:
  name: k8s-course-app
  labels:
    app: k8s-course-app
spec:
  type: ClusterIP
  selector:
    app: k8s-course-app
  ports:
    - name: http
      port: 80
      targetPort: 3000